export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_GETUSER_REQUEST = "USER_GETUSER_REQUEST";
export const USER_GETUSER_SUCCESS = "USER_GETUSER_SUCCESS";
export const USER_GETUSER_FAIL = "USER_GETUSER_FAIL";

export const USER_DELETEUSER_REQUEST = "USER_DELETEUSER_REQUEST";
export const USER_DELETEUSER_SUCCESS = "USER_DELETEUSER_SUCCESS";
export const USER_DELETEUSER_FAIL = "USER_DELETEUSER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";